{
 "title": "Oathkeeper",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(ory_oathkeeper_requests_total[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Allowed RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(ory_oathkeeper_requests_total{status_code=\"200\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Denied RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(ory_oathkeeper_requests_total{status_code!=\"200\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ory_oathkeeper_requests_total[5m])) by (instance, request)",
     "legendFormat": "{{ instance }} - {{ request }}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, avg(rate(ory_oathkeeper_requests_duration_seconds_bucket[5m])) by (le, instance))",
     "legendFormat": "{{ instance }} - p90"
    },
    {
     "expr": "histogram_quantile(0.95, avg(rate(ory_oathkeeper_requests_duration_seconds_bucket[5m])) by (le, instance))",
     "legendFormat": "{{ instance }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, avg(rate(ory_oathkeeper_requests_duration_seconds_bucket[5m])) by (le, instance))",
     "legendFormat": "{{ instance }} - p99"
    },
    {
     "expr": "histogram_quantile(1, avg(rate(ory_oathkeeper_requests_duration_seconds_bucket[5m])) by (le, instance))",
     "legendFormat": "{{ instance }} - p100"
    }
   ]
  }
 ]
}